server:
  port: 8080

spring:
  application:
    name: customers
  
  datasource:
    url: jdbc:postgresql://localhost:5432/customers_db
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.demo.shyngys: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG 